from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field


class _StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)


class InitramfsSpec(_StrictModel):
    kernel_version: str = Field(min_length=1)
    modules: list[str] = Field(default_factory=list)
    extra_files: list[Path] = Field(default_factory=list)
    compress: str = "zstd"
    hostonly: bool = False


def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_dracut_conf(spec: InitramfsSpec) -> str:
    lines: list[str] = [
        "# dracut configuration generated by distro-builder",
    ]
    if spec.modules:
        mods = " ".join(spec.modules)
        lines.append(f"add_drivers+={_quote(' ' + mods + ' ')}")
    if spec.extra_files:
        paths = " ".join(str(p) for p in spec.extra_files)
        lines.append(f"install_items+={_quote(' ' + paths + ' ')}")
    lines.append(f"compress={_quote(spec.compress)}")
    lines.append(f"hostonly={_quote('yes' if spec.hostonly else 'no')}")
    return "\n".join(lines) + "\n"


def render_dracut_command(spec: InitramfsSpec, output: Path) -> list[str]:
    argv: list[str] = ["dracut", "--force"]
    argv.extend(["--kver", spec.kernel_version])
    argv.extend(["--compress", spec.compress])
    if spec.hostonly:
        argv.append("--hostonly")
    else:
        argv.append("--no-hostonly")
    for mod in spec.modules:
        argv.extend(["--add-drivers", mod])
    for extra in spec.extra_files:
        argv.extend(["--install", str(extra)])
    argv.append(str(output))
    argv.append(spec.kernel_version)
    return argv


def write_dracut_conf(spec: InitramfsSpec, path: Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_dracut_conf(spec), encoding="utf-8")
    return path
